services:
  - type: web
    plan: free
    name: crud
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn djangocrud.asgi:application -k uvicorn.workers.UvicornWorker'